name = "SandwichMC"
author = "Sando & Redtrain22"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95b2054171086baed96c521f0bd88c01ef0c7590a871ebde2da34afe39da8805"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
