name = "SandwichMC"
author = "Sando & Redtrain22"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b628674782cd9726c945f16915b74fd4d735a81828f0c2c8189b2a2202389d8"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
