name = "SandwichMC"
author = "Sando & Redtrain22"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be61594015e588aca11e2a1f40838c841acb4bf7d15426adb38d2adb05ceff24"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
