[general.spawning]

flySpawnWeight = 0
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		flySpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000

        caveCentipedeSpawnWeight = 0
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		caveCentipedeSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000

        cockroachSpawnWeight = 0
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		cockroachSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000