[General]

	#Whether Rotten Flesh afflicts you with Rotten Stink
	ROTTEN_CONSUMPTION_ENABLED = false

["Bloody Gadfly"]

	BLOODY_GADFLY_SPAWNING_ENABLED = false

 ["Corpse Fly"]

    CORPSE_FLY_SPAWN_ENABLED = false

[Firelight]

    FIRELIGHT_SPAWNING_ENABLED = false

[Maggots]

    MAGGOTS_APPEARANCE_ENABLED = false

["Zombie Clown"]

    ZOMBIE_CLOWN_SPAWNING_ENABLED = false

 [Swarmer]

    SWARMER_SPAWNING_ENABLED = false