#The time in ticks in which a player can still be rescued from death. 20 ticks are one second. Set to 0 to disable the timer.
ticksUntilDeath = 10000
#The time in ticks it takes to rescue a player. 20 ticks are one second.
rescueActionTicks = 140
#The amount of health to respawn with when a player was rescued, out of 20.
rescueRespawnHealth = 10
#The food level to respawn with when a player was rescued, out of 20.
rescueRespawnFoodLevel = 10
#Effects applied to a player when rescued, in the format "effect|duration|amplifier"
rescueRespawnEffects = ["minecraft:water_breathing|260|0", "minecraft:resistance|50|255", "minecraft:speed|260|1"]


