#Prevent standing on bedrock at low Y levels from teleporting you to the void from these dimensions
#Example: minecraft:overworld
#
bedrockTeleportationDimensionBlacklist = ["minecraft:overworld", "minecraft:the_nether", "infinite_abyss:first_layer", "macabre:the_pit", "infinite_abyss:sixthlayer", "infinite_abyss:fourth_layer", "infinite_abyss:seventh_layer", "deeperdarker:otherside", "infinite_abyss:second_layer", "infinite_abyss:fifth_layer"]
#Changes the bedrock teleportation dimension blacklist config to be a whitelist instead
bedrockTeleportationDimensionWhitelist = false

