[general]
#Time in ticks for which the difficulty shouldnt increase at the beginning. One full minecraft day is 24000 ticks
#Range: > 0
"Difficulty Delay" = 2400
#Handles increase in difficulty regarding current difficulty.
#Format is <minimum current difficulty>-<increase every 2400 ticks>
#Example ["0-0.01","10-0.1","30-0"]
#So the difficulty increases by 0.01 every 2400 ticks (->0.1 per mc day since a mc day has 24000 ticks) till it reaches a difficulty of 10.
#Then it increases by 1 per mc day till it reaches 30 and then stops.
#If you want to use negative values use | instead of - as the delimiter.
"Difficulty Increase" = ["0.0-0.023", "300.0-0.0"]
#Wether difficulty should only increase with at least one online players or not
"Ignore Players" = false 

#Settings regarding custom ai for mobs
[ai]
#Range: 0.0 ~ 1.0
"Guardian Chance" = 0.0
#Chance for mobs to be able to summon a flying mount
#Range: 0.0 ~ 1.0
"Phantom Chance" = 0.0

#Configs regarding mobs spawning with equipment
[equipment]
#Blacklist items from whole mods. Add modid to prevent items from that mod being equipped. (For individual items use the equipment.json)
"Item Blacklist" = ["minecraft:fishingrod", "minecraft:enderpearl"]
#Base chance that a mob can have one piece of armor
#Range: 0.0 ~ 1.0
"Equipment Chance" = 0.30000001192092896
#Base chance for each additional armor pieces
#Range: 0.0 ~ 1.0
"Additional Equipment Chance" = 0.30000001192092896
#Adds additional x*difficulty% to base equip chance
#Range: 0.0 ~ 1.7976931348623157E308
"Equipment Addition" = 0.30000001192092896
#Chance for mobs to have a weapon
#Range: 0.0 ~ 1.0
"Weapon Chance" = 0.1
#Adds additional x*difficulty% to base weapon chance
#Range: 0.0 ~ 1.7976931348623157E308
"Weapon Chance Add" = 0.01000001192092896
#Base chance for each armor pieces to get enchanted
#Range: 0.0 ~ 1.0
"Enchanting Chance" = 0.10000000298023223
#Adds additional x*difficulty% to base enchanting chance
#Range: 0.0 ~ 1.7976931348623157E308
"Enchanting Addition" = 0.10000000298023223
#Chance for mobs to have an item in offhand
#Range: 0.0 ~ 1.0
"Item Equip Chance" = 0.023
#Adds additional x*difficulty% to base item chance
#Range: 0.0 ~ 1.7976931348623157E308
"Item Chance add" = 0.20000000298023224

#Settings for attribute modifiers
[attributes]
#Health will be multiplied by 1 + difficulty*0.016*x. Set to 0 to disable
#Range: 0.0 ~ 1.7976931348623157E308
"Health Increase Multiplier" = 1.5
#Health will be multiplied by at maximum this. Set to 0 means no limit
#Range: 0.0 ~ 1.7976931348623157E308
"Max Health Increase" = 4.0
#Round health to the nearest x. Set to 0 to disable
#Range: 0.0 ~ 1.7976931348623157E308
"Round HP" = 0.5
#Damage will be multiplied by 1 + difficulty*0.008*x. Set to 0 to disable
#Range: 0.0 ~ 1.7976931348623157E308
"Damage Increase Multiplier" = 0.033624179
#Damage will be multiplied by at maximum this. Set to 0 means no limit
#Range: 0.0 ~ 1.7976931348623157E308
"Max Damage Increase" = 6.0
#Knockback will be increased by difficulty*0.002*x. Set to 0 to disable
#Range: 0.0 ~ 1.7976931348623157E308
"Knockback Increase" = 0.0
#Maximum increase in knockback
#Range: 0.0 ~ 1.0
"Max Knockback" = 0.0
#Projectile Damage will be multiplied by 1 + difficulty*0.008*x. Set to 0 to disable
#Range: 0.0 ~ 1.7976931348623157E308
"Projectile Damage Increase" = 0.0
#Projectile damage will be multiplied by maximum of this
#Range: 0.0 ~ 1.7976931348623157E308
"Max Projectile Damage" = 0.0
#Explosion Damage will be multiplied by 1 + difficulty*0.003*x. Set to 0 to disable
#Range: 0.0 ~ 1.7976931348623157E308
"Explosion Damage Increase" = 0.0
#Explosion damage will be multiplied by maximum of this
#Range: 0.0 ~ 1.7976931348623157E308
"Max Explosion Damage" = 0.0