[Mobs.Spawning]
  "Min Monsters Despawning Distance" = 32

#[Mobs.Targeting]
#  # Testing disabling this due to server lag.
#  "Better Path Finding" = false

[Mobs.Anti-Cheese]
  "Prevent Boating & Minecarting" = false
  "Break trapping vehicles" = false