[Mobs]
	#Endermen will make the player's item fall from his hands. Add/remove mobs via the enhancedai:can_disrupt_item entity type tag
	"Enable Item Disruption" = false

[Mobs.Spawning]
  "Min Monsters Despawning Distance" = 32

#[Mobs.Targeting]
#  # Testing disabling this due to server lag.
#  "Better Path Finding" = false

[Mobs.Anti-Cheese]
  "Prevent Boating & Minecarting" = false
  "Break trapping vehicles" = false

  [Animals]
	#Make animals fight back or be scared by players. Use the entity type tag enhancedai:can_fight_back and enhancedai:can_be_scared_by_players to add/remove animals.
	"Enable Animals Scared Attack" = false

	#Make animals flee/fight back when one is attacked
	"Enable Animals Group Flee" = false

	#Makes animals not tempted by food. Use the entity type tag enhancedai:can_ignore_food_temptation to change animals.
	"Enable Not Tempted Animals" = false